name: pnpm

description: Setup node and pnpm

outputs:
  # Required for $GITHUB_OUTPUT to work in composite action.
  STORE_PATH:
    value: ${{ steps.store.outputs.STORE_PATH }}

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

    - name: Install Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: .node-version
        registry-url: "https://registry.npmjs.org"
        # see pnpm cache setting below

    - name: Get pnpm store directory
      id: store
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Save pnpm cache on main
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      # if: ${{ github.ref_name == 'main' }}
      with:
        path: ${{ steps.store.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Restore pnpm cache
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ steps.store.outputs.STORE_PATH }}
        key: |
          ${{ runner.os }}-pnpm-store-

    - run: pnpm install --frozen-lockfile
      shell: bash
